{{- if .Values.service.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homarr.fullname" . }}-local
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
spec:
  {{- with .Values.service.internal }}
  type: {{ .type }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
    protocol: {{ .protocol }}
    name: {{ .name }}
  {{- end }}
  selector:
    {{- include "homarr.selectorLabels" . | nindent 4 }}
{{- end }}
