{{- if .Values.service.main.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
spec:
  {{- with .Values.service.main }}
  type: {{ .type }}
  ports:
  - port: {{ .ports.http.port }}
    targetPort: {{ .ports.http.targetPort }}
    protocol: {{ .ports.http.protocol }}
    name: {{ .ports.http.name }}
  {{- end }}
  selector:
    {{- include "prowlarr.selectorLabels" . | nindent 4 }}
{{- end }}
